### PR TITLE
Fix CSL dependent style support

### LINKED ISSUE #105: Using dependent CSLs with pandoc-citeproc?
I have run into an issue with [dependent CSLs](https://github.com/citation-style-language/styles/tree/master/dependent) and pandoc-citeproc. I think citeproc isn't able to figure out the dependencies of the CSL and leaves all the citations as the **???** placeholders. I tried this with the [bmc-bioinformatics.csl](https://github.com/citation-style-language/styles/blob/master/dependent/bmc-bioinformatics.csl) file.

### PR DESCRIPTION
**Pull request by timtylin**
Parsing bug introduced while moving to http-conduit.
Closes #105

### CODE REVIEW

**Comment by timtylin** [comment]
I think this should be okay for GHC 7.10, but I don't have the ability to check atm

**Comment by jgm** [comment]
Do we have any tests for dependent styles?  If not, would you have any interest in adding one?  It has been a while since I looked at dependent styles, so I can't recall quite how they work.

**Comment by timtylin** [comment]
I thought about it, but wasn't sure about making http requests in the unit test if none existed already. If we want to avoid that, maybe we need to refactor out the xml filter/Axis that picks the parent and test that separately?

**Comment by jgm** [comment]
Good point.  This is getting overly elaborate, but I suppose
we could have the test suite spin up a web server and serve
the parent on localhost, adjusting the child to point to
that?

+++ Tim T.Y. Lin [Mar 02 15 14:24 ]:

**Comment by timtylin** [comment]
> This is getting overly elaborate, but I suppose
we could have the test suite spin up a web server and serve
the parent on localhost, adjusting the child to point to
that?

Sure, nothing like a good yak shave ;)

I don't know how to setup a listening socket from scratch without depending on `network`. But if we want to keep it practical, I guess we have two simple options:

1. Just test that the correct parent URL is parsed. This would require a refactoring but can be part of the standard test suite.

2. Fully test that calling `Text.CSL.Parse.readCSLFile` on a dependent CSL matches calling it on the fully qualified URL string of its parent (assuming locale doesn't change). Hide it behind a CPP pragma or a cli option so that it won't be run by default.

**Pull request merged**
