### PR TITLE
Migrate to HsYAML

### PR DESCRIPTION
**Pull request by vijayphoenix**
Replaced some Yaml part with HsYAML-aeson.

HsYAML-0.2 and HsYAML-aeson-0.2 will be released very soon!

### CODE REVIEW

**Comment by jgm** [comment]
What is still blocking us from getting rid of `yaml` altogether?

**Comment by vijayphoenix** [comment]
> What is still blocking us from getting rid of `yaml` altogether?

We can easily replace it easily by building a layer atop the Event API provided by HsYAML.
I did not replace it because I could not understand the intricacies of the code.

**Comment by hvr** [comment]
@jgm To be more precise; We already have support for emitting YAML at the high-level schema aware `ToYAML`-class style API, or operating at the Node/Graph-level, as well as a more low-level Event-style API

the part we don't have yet is that middle ground the experimental-marked `Data.Yaml.Builder` module in `yaml-0.11` has; but we're still debating whether to provide a small compat-layer emulating that API, or whether it'd be better to rewrite the code in pandoc-citepoc to the high-level ToYAML-class or Node/Graph level API.

Do you have any preferences?

**Comment by vijayphoenix** [comment]
> It's hard to say without seeing the high-level API (and it looks like 2.0 is not released yet).
> But if it provides a ToYaml class, and if it wouldn't be too hard to rewrite pandoc-citeproc to use that API, then I don't see why not.

You can find the HsYAML-0.2 `ToYAML` class documentation [here](https://hackage.haskell.org/package/HsYAML-0.2.0.0/candidate/docs/Data-YAML.html#t:ToYAML)

Click [here](https://hackage.haskell.org/package/HsYAML-aeson-0.2.0.0/candidate) to see the HsYAML-aeson-0.2 documentation.

**Comment by jgm** [comment]
@hvr will we be getting an HsYAML-0.2 release soon?

**Comment by vijayphoenix** [comment]
> @hvr will we be getting an HsYAML-0.2 release soon?
> [EDIT: I mean, HsYAML-aeson-0.2]

@jgm it will be released in a few hours

**Comment by jgm** [comment]
I've merged this manually.

**Comment by hvr** [comment]
@jgm fyi, http://hackage.haskell.org/package/HsYAML-aeson-0.2.0.0 has been released; be aware there were some last-minute changes to the typesignatures

**Pull request closed without merging**
