### PR TITLE
Add flag to silence all warnings

### PR DESCRIPTION
**Pull request by tarleb**
Introduce new command line flag `--quiet`/`-q` which can be used to
suppress all warnings.

### CODE REVIEW

**Comment by tarleb** [comment]
Motivated by [this discussion](https://groups.google.com/d/topic/pandoc-discuss/dT6eRRlrxJg/discussion). It should be possible to rewrite the mentioned filter such that there are no warnings, but being able to quiet warnings would be easier (and probably less fragile).

**Comment by jgm** [comment]
Looks good.  `man/pandoc-citeproc.1.md` also needs updating.

**Comment by tarleb** [comment]
Done. Seems like checks fail because Travis CI runs out of memory when compiling pandoc's LaTeX reader.

**Comment by jgm** [comment]
I'm baffled about the CI failures.  (I already commented out the cabal builds, which were getting hung up on Text.CSL.Style...)  We compile pandoc all the time on travis; what is different about this repository?

**Pull request merged**
