### PR TITLE
locators: allows parsing balanced brackets in locators like 1(2)(a)(i)

### PR DESCRIPTION
**Pull request by cormacrelf**
This is useful for citing legislation. It is necessary to be more liberal
in locator parsing because some styles put other elements after a locator,
like short titles in the case of AGLC, and if you can't parse a locator,
it gets rendered after, or worse, split in half.

This breaks the issue61 (#61) tests, but multiple locator types in
the same cite have never been supported, especially not by CSL.
See issue #275 for more details on that.
'VIII, 89' now appears to parse as a plural form of `pages`, not as
whatever it was doing before. So now there's a `Str "pp.",Space` before
each.

The new issue61 behaviour may or may not be more correct. If it isn't clear
what the correct behaviour is for that style, maybe it's worth deleting
the test entirely.

### CODE REVIEW

**Comment by cormacrelf** [comment]
@jgm I wrote a test case, but Prelude.read fails to read the native files. I thought I did everything as you described; have I missed anything?

**Comment by cormacrelf** [comment]
Also the code's a bit messy and I'm new to parsec but that can be fixed.

**Comment by jgm** [comment]
For easy reference, here's the difference in issue 61 tests:
```
[issue61.in.native] FAILED
--- expected	2018-11-09 15:45:44.336556302 +0000
+++ actual	2018-11-09 15:45:44.336556302 +0000
@@ -2,7 +2,7 @@
 [Header 1 ("text",[],[]) [Str "Text"]
-,Para [Str "Foo",Str "",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "VIII,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 1}] [Note [Para [Str "John",Space,Str "Doe,",Space,Emph [Str "Title"],Space,Str "(Publisher,",Space,Str "1985),",Space,Str "VIII,",Space,Str "89."]]]]
-,Para [Str "Foo",Str "",Cite [Citation {citationId = "roe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "III,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 2}] [Note [Para [Str "Rob",Space,Str "Roe,",Space,Emph [Str "Title"],Space,Str "(Publisher,",Space,Str "1985),",Space,Str "III,",Space,Str "89."]]]]
-,Para [Str "Foo",Str "",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "LVIII,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 3}] [Note [Para [Str "Doe,",Space,Str "LVIII,",Space,Str "89."]]]]
-,Para [Str "Foo",Str "",Cite [Citation {citationId = "roe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "MVIII,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 4}] [Note [Para [Str "Roe,",Space,Str "MVIII,",Space,Str "89."]]]]
-,Para [Str "Foo",Str "",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "CL,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 5}] [Note [Para [Str "Doe,",Space,Str "CL,",Space,Str "89."]]]]
+,Para [Str "Foo",Str "",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "VIII,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 1}] [Note [Para [Str "John",Space,Str "Doe,",Space,Emph [Str "Title"],Space,Str "(Publisher,",Space,Str "1985),",Space,Str "pp.",Space,Str "VIII,",Space,Str "89."]]]]
+,Para [Str "Foo",Str "",Cite [Citation {citationId = "roe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "III,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 2}] [Note [Para [Str "Rob",Space,Str "Roe,",Space,Emph [Str "Title"],Space,Str "(Publisher,",Space,Str "1985),",Space,Str "pp.",Space,Str "III,",Space,Str "89."]]]]
+,Para [Str "Foo",Str "",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "LVIII,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 3}] [Note [Para [Str "Doe,",Space,Str "pp.",Space,Str "LVIII,",Space,Str "89."]]]]
+,Para [Str "Foo",Str "",Cite [Citation {citationId = "roe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "MVIII,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 4}] [Note [Para [Str "Roe,",Space,Str "pp.",Space,Str "MVIII,",Space,Str "89."]]]]
+,Para [Str "Foo",Str "",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [Str ",",Space,Str "CL,",Space,Str "89"], citationMode = NormalCitation, citationNoteNum = 0, citationHash = 5}] [Note [Para [Str "Doe,",Space,Str "pp.",Space,Str "CL,",Space,Str "89."]]]]
 ,Header 1 ("references",["unnumbered"],[]) [Str "References"]
```

I think the original behavior is better: not recognizing `VIII, 89` as a page number (and especially not as a page range), and just treating it as a plain suffix.

**Comment by cormacrelf** [comment]
I don’t think it’s a matter of choosing a good behaviour. Sometimes people will want to specify a pre-start page number in Roman numerals, and as a barely configurable tool we can’t judge. There simply isn’t a syntax for being clear about this. CSL itself only provides for a single locator, which is incredibly short-sighted, and the reality (which everyone has experienced) is that we’re now trying to work out when in a syntax block designed for one locator we should end the parse. And we’re treating the result as a plain string anyway, so it really is just a problem of letting people specify when the end is.

Why not a new syntax to be precise about how long the locator string is? 

[@citekey{3, 17, pt III div 4 s 19(1)(a)} suffix here] seems like a good fit.

**Comment by cormacrelf** [comment]
I also say this as a user of a style which places elements after the locator and before the suffix, so choosing an arbitrary end isn’t an option. Unless you want:

*Long Named Act 2009* (Cth) s 52 (‘*Short Title*’) (2)(a)

**Comment by jgm** [comment]
I think that adding an optional syntax for clearly indicating a complex locator might be a good plan.  It should be optional, though; we don't want to break anything that currently works.  Using `{}` seems as good an idea as any.  So you could do
```
[@citekey, {p. 33(a)B-1}]
```
or
```
[@citekey, {33(a)B-1}, optional suffix, using default locator type]
```
or
```
[@citekey{33(a)B-1}, with no space and comma]
```
or
```
[@citekey, 33, just like before, with a simple locator]
```

**Comment by jgm** [comment]
While it may be worth considering some syntax for indicating locators, I don't think it's actually necessary for this issue.  The main issue is to allow balanced braces and parens in locators.  This is needed for the following to work:
```
[@buchanan:puzzle, p. 1(a)]
```
since currently the `(a)` is parsed as a suffix and not part of the locator.

But this doesn't entail parsing `VIII, 89` as a locator, instead of a plain suffix (as it is currently treated).

Can you clarify why we're also seeing this divergence?  Isn't it possible to implement this change without affecting the #61 test?

**Comment by jgm** [comment]
> pre-start page number in Roman numerals, and as a barely configurable tool we can’t judge. There simply isn’t a syntax for being clear about this. 

To be clear, there is:

`[@citekey, xi]` gives you a suffix `xi`.
`[@citekey, p. xi]` gives you a (page) locator `xi`.

Pandoc allows you to omit the explicit locator type (e.g. `p.`, `vol.`, etc.) only when you have pure digits, and then it defaults to "page."  But this is a convenience.

**Comment by cormacrelf** [comment]
Very good. I think I may have missed something about required digits, I think you’re right about not breaking 61. And while I have my head in the code, I might give the syntax a try, for a separate PR.

**Comment by cormacrelf** [comment]
Ok, I've essentially rewritten it. All test cases (and a ton of new ones) pass. There's an sneaky extra commit with the new syntax added.

The code is a little complex, but as I described [here](https://github.com/cormacrelf/pandoc-citeproc/tree/c4ec8535837fddc539c230651197dec118a99cbe/src/Text/CSL/Pandoc.hs#L445-L475) there are a few difficult requirements here.

* There are 2 levels of 'digit-ness' a word can have; `requireDigits`, and `requireRomansOrDigits`.
  * `requireDigits` (must have 0-9 in there) is needed directly after a citekey (implicit "page" citeLabel). This covers the VI, 89 compatibility.
  * `requireRomansOrDigits` is a softer requirement, but is enough to differentiate a suffix comment like "(hi)" from a page number like "(1)" or "(a)(ii)". It's also implemented where romans/other segments are parsed and then percolated up, not at the top as a guard.
* There are other various details about braces and 1.2.3 etc that you can understand from `./mktest.sh locators-integrated.md -r` and reading the code.
* The new syntax is pretty much as described above. It was vastly simpler to build. `./mktest.sh locators-delimited.md -r` is essentially the spec.

In all, the user-facing syntax summary on Pandoc's Markdown boils down to:

> When you omit a locator term, Pandoc detects locators with arabic numbers in them, like `[@smith, 20, 42-43]` and also `[@document, 3(a), 4.4.8, [7.6], 7A(i)-(iv)]`.
> If you specify a locator term, Pandoc also detects roman numerals by themselves: `[@smith, pp. iv, vi-xi, (xv)-(xvii)]`
> If you need to let Pandoc know what is a locator and what isn't, you can: `[@smith{ii, A, D-Z}, suffix]` or with the optional comma, space and locator term: `[@smith, {pts. B, 3C, Z}]`

**Pull request merged**
